# Generated by Django 2.2.24 on 2021-08-25 07:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0010_auto_20190326_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='allowed_lecture',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='contest',
            name='allowed_school',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
