# Generated by Django 2.2.24 on 2021-08-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20210703_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.TextField(null=True),
        ),
    ]
